/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  admin: {
    AdminAuth: () => import('#controllers/admin/admin_auth_controller'),
    AdminCompliance: () => import('#controllers/admin/admin_compliance_controller'),
    AdminInvitation: () => import('#controllers/admin/admin_invitation_controller'),
    AdminProfile: () => import('#controllers/admin/admin_profile_controller'),
    AuditLogs: () => import('#controllers/admin/audit_logs_controller'),
    RoleManagement: () => import('#controllers/admin/role_management_controller'),
    TeamManagement: () => import('#controllers/admin/team_management_controller'),
  },
  Compliance: () => import('#controllers/compliance_controller'),
  Dashboards: () => import('#controllers/dashboards_controller'),
  ForgotPasswords: () => import('#controllers/forgot_passwords_controller'),
  IbkrConnect: () => import('#controllers/ibkr_connect_controller'),
  Mfas: () => import('#controllers/mfas_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PersonalCompliance: () => import('#controllers/personal_compliance_controller'),
  Profile: () => import('#controllers/profile_controller'),
  RegulatedbusinessCompliance: () => import('#controllers/regulatedbusiness_compliance_controller'),
  SumsubWebhook: () => import('#controllers/sumsub_webhook_controller'),
  VerifyEmails: () => import('#controllers/verify_emails_controller'),
}
