/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Compliance: () => import('#controllers/compliance_controller'),
  Dashboards: () => import('#controllers/dashboards_controller'),
  ForgotPasswords: () => import('#controllers/forgot_passwords_controller'),
  Mfas: () => import('#controllers/mfas_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PersonalCompliance: () => import('#controllers/personal_compliance_controller'),
  Profile: () => import('#controllers/profile_controller'),
  SumsubWebhook: () => import('#controllers/sumsub_webhook_controller'),
  VerifyEmails: () => import('#controllers/verify_emails_controller'),
}
